### ISSUE TITLE
Crash on launch

### ISSUE THREAD

**Issue by Sunekaer** [CodenameRevy/Additional-Bars#12]
Hi 

One of our players are getting a crash on launch
Log: https://hastebin.com/zijuviboja.sql

additionalbars-1.3.5
forge-1.15.2-31.1.87

**Comment by CodenameRevy** [comment]
This is not the issue with my mod, as I am able to launch the mod on forge 31.2.9
Based on the [original log](https://paste.feed-the-beast.com/view/0a881427#L551), from what I can see, the mod that crashes the game has a modID 'animalcrops' (line 559)
Also, your modpack has a lot of broken mods (the 'Potentially Dangerous alternative prefix `modid` for name `nameid`, expected `minecraft\modid`. This could be a intended override, but in most cases indicates a broken mod.' at every line from 29 to 32, 37 to 115, 179 to 181 and 288 to 518, also your KubeJS mod displays a lot of standard errors), you should update them, and forge, to the latest versions if you haven't already.

If you have any questions (regarding Additional Bars mod) feel free to ask here.

**Comment by Sunekaer** [comment]
Hi

If you see line 120 in the original log, your mod fails to create mod instance, which is causing for the crash and not animalcrops, Forge is weird and continues trying to run mods after it crashed and therefore its saying another mod in the crash log it self.. 

https://github.com/KnightMiner/AnimalCrops/issues/7
https://github.com/MinecraftForge/MinecraftForge/issues/6374

Also, I had the user remove your mod and test, and he can load the game just fine

**Comment by CodenameRevy** [comment]
Huh, I'm going to test this for now, but don't expect an update for the next two weeks because I'm busy with exams... Anyways, can you send me a list of the mods in the modpack?

I'll reopen this for now.

**Comment by Sunekaer** [comment]
Modlist: https://s1.sunekaer.com/t/omnia_modlist.html

**Comment by CodenameRevy** [comment]
Ok, so this is weird.
I've tested the latest versions of mods from the list (Mods that are no longer available are: Lithium (Forge), and mods that need to be added: Collective), and the erroring mod for me is Industrial Foregoing, BUT the crash log shows that also Animal Crops is causing the crash at the same event as before ([src/main/java/knightminer/animalcrops/client/ClientEvents#registerBlockColors](https://github.com/KnightMiner/AnimalCrops/blob/28940a2585ebd063f75e948dc7b8e3c71ba92388/src/main/java/knightminer/animalcrops/client/ClientEvents.java#L46) @ line 49).

I've tested Animal Crops and Additional Bars separately, but it doesn't cause a crash. So this isn't incompatibility issue with my mod.
I suggest you to try to update all the mods in the mod pack and try to find the culprit mod, because I don't think that either Industrial Foregoing or Additional Bars are causing a crash.

A few logs that might be useful:

Mod debug list: https://hastebin.com/adujuhotuj.rb
Debug log: https://paste.feed-the-beast.com/view/7b7ce5d7
Crash log: https://hastebin.com/ezirukogig.rb

I will close this issue in 48h.
